version: '3.4'
services:
  nginx:
    image: nginx:1.13-alpine
    container_name: demo-frontend
    depends_on:
      - nodejs
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./docker/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  nodejs:
    build:
      context: .
    container_name: demo-backend
    depends_on:
      - couchbase
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    environment:
      DEBUG: demo*
      COUCHBASE_URI: demo-db
      COUCHBASE_BUCKET: demo
      COUCHBASE_USERNAME: Administrator
      COUCHBASE_PASSWORD: password
  couchbase:
    image: bentonam/couchbase-docker:enterprise-5.0.1
    container_name: demo-db
    ports:
      - 8091-8094:8091-8094
      - 11210-11211:11210-11211
    environment:
      NODE_TYPE: DEFAULT
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
      SERVICES: data,index,query
      CLUSTER_RAMSIZE: 500
      BUCKET: demo
      ENABLE_FLUSH: 1
      RBAC_USERNAME: demo_user
      RBAC_PASSWORD: password
      RBAC_ROLES: admin
