version: '3.4'
services:
  web:
    image: nginx:1.13-alpine
    container_name: demo-web
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/mime.types:/etc/nginx/mime.types:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  backend:
    build:
      context: ./backend
    container_name: demo-backend
    depends_on:
      - couchbase
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 8081:8081
    environment:
      DEBUG: demo*
      COUCHBASE_URI: demo-db
      COUCHBASE_BUCKET: demo
      COUCHBASE_USERNAME: demo_user
      COUCHBASE_PASSWORD: password
  frontend:
    build:
      context: ./frontend
    container_name: demo-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/usr/frontend/src
    ports:
      - 8080:8080
    environment:
      HOST: demo-frontend
  couchbase:
    image: bentonam/couchbase-docker:enterprise-5.0.1
    container_name: demo-db
    ports:
      - 8091-8094:8091-8094
    environment:
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
      SERVICES: data,index,query
      BUCKET: demo
      RBAC_USERNAME: demo_user
      RBAC_PASSWORD: password
